// app/layout.tsx

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import { ThemeProvider } from 'next-themes'; // <-- 1. Impor ThemeProvider

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'AISAVINS',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 2. Tambahkan suppressHydrationWarning di sini
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* 3. Bungkus semua yang ada di dalam body dengan ThemeProvider */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster 
            position="top-right" 
            richColors 
            toastOptions={{ classNames: { toast: 'toast-bounce' } }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}